package lld.elevator;

public enum FloorNumber {
    FLOOR_NUMBER1,
    FLOOR_NUMBER2,
    FLOOR_NUMBER3,
    FLOOR_NUMBER4,
    FLOOR_NUMBER5,
    FLOOR_NUMBER6,
    FLOOR_NUMBER7,
    FLOOR_NUMBER8,
    FLOOR_NUMBER9,
    FLOOR_NUMBER10,
    FLOOR_NUMBER11,
    FLOOR_NUMBER12,
    FLOOR_NUMBER13,
    FLOOR_NUMBER14,
    FLOOR_NUMBER15;
}
